version: "3.8"

services:
  volume_vision:
    image: polehntim/volume-vision:0.0.1bata
    container_name: volume_vision
    restart: unless-stopped
    ports:
      - "5100:5100"
    volumes:
      - volume_vision_data:/data
    environment:
      - DATA_DIR=/data
      - APP_PASSWORD=${APP_PASSWORD:-changeme}
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - SPLIT_TRAIN=0.70
      - SPLIT_VAL=0.20
      - SPLIT_TEST=0.10

volumes:
  volume_vision_data:
