services:
  app_proxy:
    environment:
      APP_HOST: volume-vision_server_1
      APP_PORT: 5100
    container_name: volume-vision_app_proxy_1

  server:
    image: polehntim/volume-vision:latest
    container_name: volume-vision_server_1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - '5101:5100'
    environment:
      DATA_DIR: /data
      APP_PASSWORD: ${APP_PASSWORD:-changeme}
      SECRET_KEY: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    tmpfs:
      - /tmp:size=64m,mode=1777
    mem_limit: 256m
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
