version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: volume-vision_server_1
      APP_PORT: 5100

  server:
    image: polehntim/volume-vision:0.0.1bata
    restart: on-failure
    stop_grace_period: 1m
    environment:
      DATA_DIR: /data
      SECRET_KEY: $APP_SEED
      APP_PASSWORD: ${APP_PASSWORD:-changeme}
      FLASK_ENV: production
      SPLIT_TRAIN: "0.70"
      SPLIT_VAL: "0.20"
      SPLIT_TEST: "0.10"
    volumes:
      - ${APP_DATA_DIR}/data/volume-vision:/data
